### ISSUE TITLE
error 404 when apt-get install & can't apt-get update

### ISSUE THREAD

**Issue by felicitia** [DavidBurela/riscv-emulator-docker-image#5]
Thanks for the image!

After ssh into the Debian, I was not able to do `apt-get install` on anything due to error 404. It should be easily resolved by `apt-get update` usually, but when `apt-get update`, I got a public key error `err:1 http://deb.debian.org/debian-ports unstable InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B523E5F3FC4E5F2C NO_PUBKEY 8D69674688B6CB36`. 

I tried `apt-key adv` to add the public keys but the error message says `E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation`. Then it goes back to the original `apt-get install` problem as I can't install new packages like gnupg. 

Has anyone had this issue before? Thanks!

**Comment by krydos** [comment]
@felicitia I just built the docker image from scratch and I didn't see this particular issue. 
I wonder if it's something related to some expired keys or some changes on the debian repo side. 

I believe you can solve by re-building the Docker image on your machine. 

While I tried to build it I noticed few issues which have been solved in this [Dockerifle](https://github.com/krydos/riscv-emulator-docker-image-for-arm/blob/fix-build-process/Dockerfile). 
Using it you should be able to build with no issues. `apt-get update` stuff should work too. Seems working on my end.

**Comment by felicitia** [comment]
Thank you so much @krydos ! I'll give it a try based on your suggestions. I'm closing the issue for now since it's not a common issue for everybody. Thank you for replying to me!
